# Generated by Django 4.1.7 on 2023-06-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='none', max_length=11),
        ),
    ]
