# Generated by Django 4.1.7 on 2023-06-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_remove_user_name_user_address_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
